// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppHub.Models;

namespace WebAppHub.Migrations
{
    [DbContext(typeof(DbContextTodo))]
    [Migration("20200619212507_UserConnectedMigration")]
    partial class UserConnectedMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("WebAppHub.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(150);

                    b.Property<bool>("Done")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("todos");
                });

            modelBuilder.Entity("WebAppHub.Models.UserConnected", b =>
                {
                    b.Property<string>("ConnectedId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConnectedId");

                    b.ToTable("user_connected");
                });
#pragma warning restore 612, 618
        }
    }
}
